@host = http://localhost:8080/api/v1

### Save Transaction
POST {{host}}/fixed_income/transaction
Content-Type: application/json

{
  "assetType": "DIRECT_TREASURE",
  "description": "Tesouro IPCA+ 2026",
  "profitabilityInPercent": 6.24,
  "indexer": "IPCA",
  "liquidity": "diáriaa",
  "expiresIn": "2026-08-15",
  "totalInvested": 4996.12,
  "units": 1.6,
  "operationDate": "2022-08-15"
}

### Delete by ID
DELETE {{host}}/fixed_income/transaction/1

### Find all Transactions (default PageInfo)
GET {{host}}/fixed_income/transaction

### Find all Transactions (custom PageInfo)
GET {{host}}/fixed_income/transaction
Content-Type: application/json

{
  "pageNumber": 0,
  "pageSize": 10,
  "orders": [
    {
      "direction": "ASC",
      "property": "indexer"
    },
    {
      "direction": "DESC",
      "property": "expiresIn"
    }
  ]
}