### Save Transaction
POST {{fixed-income-transaction-endpoint}}
Content-Type: application/json

{
  "assetType": "DIRECT_TREASURE",
  "description": "Tesouro IPCA+ 2026",
  "profitabilityInPercent": 6.24,
  "indexer": "IPCA",
  "liquidity": "diária",
  "expiresIn": "2026-08-15",
  "totalInvested": 4996.12,
  "units": 1.6,
  "operationDate": "2022-08-15"
}

### Delete by ID
DELETE {{fixed-income-transaction-endpoint}}/1

### Find all Transactions (default PageInfo)
GET {{fixed-income-transaction-endpoint}}

### Find all Transactions (custom PageInfo)
GET {{fixed-income-transaction-endpoint}}
Content-Type: application/json

{
  "pageNumber": 0,
  "pageSize": 10,
  "orders": [
    {
      "direction": "ASC",
      "property": "indexer"
    },
    {
      "direction": "DESC",
      "property": "expiresIn"
    }
  ]
}