### Save Transaction
POST {{base-url}}/variable_income/transaction
Content-Type: application/json

{
  "assetCode": "BBAS3",
  "assetType": "STOCK",
  "operationDate": "2022-09-09",
  "operationType": "BUY",
  "operationAverageCost": 41.20,
  "numberOfShares": 10
}

### Delete Transaction by ID
DELETE {{base-url}}/variable_income/transaction/21

### Find all Transactions (default PageInfo)
GET {{base-url}}/variable_income/transaction

### Find all Transactions (custom PageInfo)
GET {{base-url}}/variable_income/transaction
Content-Type: application/json

{
  "pageNumber": 0,
  "pageSize": 30,
  "orders": [
    {
      "direction": "DESC",
      "property": "operationDate"
    },
    {
    "direction": "ASC",
    "property": "assetCode"
    }
  ]
}

### Find all Transaction of BBAS3 (default PageInfo)
GET {{base-url}}/variable_income/transaction/bbas3

### Find all Transaction by AssetType "STOCK" (default PageInfo)
GET {{base-url}}/variable_income/transaction/assetType/STOCK

### Find all Transaction with operation date of 09/09/2022 (default PageInfo)
GET {{base-url}}/variable_income/transaction/operationDate/2022-09-09