spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

finances-data-provider:
  base-url: http://localhost:3000
  endpoints:
    announcements: ${finances-data-provider.base-url}/announcements
    real-state-fund: ${finances-data-provider.base-url}/real-state-fund
    stock: ${finances-data-provider.base-url}/stock