filebeat.inputs:
  - type: filestream
    id: finances-backend-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
      - /usr/share/filebeat/logs/*.json

output.logstash:
  hosts: [ "logstash:5044" ]